# This workflow will run daily to check for Nifty alerts1

name: Nifty Alert System

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 02:30 AM UTC - change as needed.  10AM UTC is 3:30 PM IST
  push: #optional, to run on push as well
    branches:
      - main

jobs:
  check_alerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Or a more recent version if you need it
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas  # Install yfinance and pandas
          #  Install any other dependencies, including telegram_bot, if needed.
          #  If telegram_bot is in a separate file, make sure it's in the repository.
          #  For example: pip install -r requirements.txt
      - name: Run the Nifty alert script
        env:
          # Set any environment variables your script needs, such as Telegram bot token
          # TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          # TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python nifty_alert.py # change to the name of your main file.
