# This workflow will run daily to check for Nifty alerts and send Telegram notification
name: Nifty Alert System

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 10:00 AM UTC (3:30 PM IST)
  push: # Optional, to run on push as well
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_alerts:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access your code.  Crucial.
      - uses: actions/checkout@v4

      # Sets up Python 3.9.  Required for running the Python script.
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Installs the necessary Python packages.  Essential for the script to function.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Ensure pip is up-to-date
          pip install yfinance pandas python-telegram-bot  # Install required libraries
          pip install python-telegram-bot requests
          # If you have a requirements.txt file, use this instead:
          # pip install -r requirements.txt
              
      # Runs the Nifty alert script.  This is where the core logic is executed.
     
      - name: Execute Nifty Alert Script
        env:
          TELEGRAM_BOT_TOKEN: "8017759392:AAEwM-W-y83lLXTjlPl8sC_aBmizuIrFXnU"
          TELEGRAM_CHAT_ID: "711856868"
        run: python3 nifty_alert.py

